ingester:
  enable:
    openphish: true
    phishtank: false #false
    urlhaus: true
    certstream: true
    manual: true

processor:
  thresholds:
    scam: 0.5
    non_scam: 0.5

  # Heuristics (simplified defaults)
  forbidden_keywords: ["login", "signin", "verify", "password", "2fa", "wallet", "airdrop", "invoice", "refund"]
  parking_signatures: ["domain for sale", "this domain is for sale", "sedo", "bodis", "parking"]
  kit_paths: ["/owa", "/office365", "/webmail", "/login", "/verify", "/invoice"]

  # Brand-scoped toggles: # SAMPLE CONFIGURATION CHANGE HERE
  whitelist_keywords: ["pages.dev", "vercel.app", "webflow.io", "blogspot.", "github.io", "dbs.com", "dbs.com.sg", "posb.com.sg", "dbs.com.hk", "dbs.com.tw", "dbs.com.cn", "dbs.com.mo", "dbsbank.in", "dbs.co.id", "dbsprivatebank.com"]
  blacklist_keywords: ["dbs", "dbsbank", "dbs-bank", "posb", "paylah", "digibank", "dbslogin", "dbs-verify", "dbsverify", "dbs-secure", "dbsupdate", "dbs-otp"]

brands: # SAMPLE CONFIGURATION CHANGE HERE
  - name: "DBS Bank"
    valid_domains: ["dbs.com", "dbs.com.sg", "posb.com.sg", "dbs.com.hk", "dbs.com.tw", "dbs.com.cn", "dbs.com.mo", "dbsbank.in", "dbs.co.id", "dbsprivatebank.com"]
    domain_accept_keywords: ["dbs.", ".dbs", "dbsbank",b "dbs-bank", "posb", "paylah", "digibank"]
    domain_reject_keywords: []

  - name: "UOB Bank"
    valid_domains: ["uob.com.sg", "uobgroup.com"]
    domain_accept_keywords: ["uob", "uobbank", "uob-bank"]
    domain_reject_keywords: []

counter:
  enable: true
  interval_s: 60